db:
  host: "localhost"
  analysis_db: mev_analysis
  trace_db: trace_db

chain: Ethereum

paths:
  ABI: "./ABIs"
  temp_abi_map: "./event_sign.txt"
  hex_abi_map: "./event_sign.json"
  decoded_logs: "./decoded_logs.csv"

filter-events:
  - Swap
  - Transfer
  - Deposite
  - Withdraw
  - Borrow
  - RepayBorrow
  - Repay
