rpc: "https://compatible-omniscient-fog.quiknode.pro/8f73d7a41f012203bc2bd471fc032e9456c4e152/"
#https://ethereum.publicnode.com

db: 
  host: "localhost"
  db_name: mev_analysis

paths:
  ABI: "./ABIs"
  temp_abi_map: "./event_sign.txt"
  hex_abi_map: "./event_sign.json"
  decoded_logs: "./decoded_logs.csv"

filter-events:
  - Swap
  - Transfer
  - Deposite
  - Withdraw
  - Borrow
  - RepayBorrow
  - Repay
